package Input <<Rectangle>> {
  package "AnnotatedFiles" <<Rectangle>> {
  }
  package "ConfigFile" <<Rectangle>> {
  }
  package "JSONSchemaFile" <<Rectangle>> {
  }

  AnnotatedFiles -[hidden]-> ConfigFile
  ConfigFile -[hidden]-> JSONSchemaFile
}

interface SwaggerGen {

}

class ConfigMapper As "???" {

}

class JsonObjectMapper {

}

AnnotatedFiles .> SwaggerGen
ConfigFile .> ConfigMapper
JSONSchemaFile .> JsonObjectMapper

package ResourceSpace <<Rectangle>> {
  class rsa As "Annotation Objects" {
    []Annotation
  }
  class rsc As "Config Object" {
    Config
  }
  class rsjs As "JSON Schema Objects" {
    []JsonSchema
  }

  rsa -[hidden]-> rsc
  rsc -[hidden]-> rsjs
}

SwaggerGen .> rsa
ConfigMapper .> rsc
JsonObjectMapper .> rsjs

package Factory <<Rectangle>> {

}

rsa .> Factory
rsc .> Factory
rsjs .> Factory

package DomainSpace <<Rectangle>> {
  class dsp As "Path Object" {
    []Path
  }
  class dsc As "Content Object" {
    []Schema
  }
  dsp -[hidden]-> dsc
}

Factory .> dsp
Factory .> dsc

class SwaggerWriter {

}

dsp .> SwaggerWriter
dsc .> SwaggerWriter

SwaggerWriter .> Output

package Output <<Rectangle>> {
}
